语句结束

     换行；
     同一行中使用分号隔开多条语句。

### 条件语句

```python
if expression:
    pass
elif expression:
    statements
else:
    statements
```

### 循环与迭代

for、while 语句，无 switch、case

```python
while expression:
        statements

for i in s:
        statements
```
> for 仅适用于可迭代对象（包括内置的序列类型，如 列表、元组、字符串）
>
> 变量 i 称为 * 迭代变量 *

迭代中使用的是元素大小完全一致的序列，则可

```python
for x,y,z in s:
    statements
```

当循环时，除了数据值外，还需要跟踪数字索引，如

```python
i = 0
for i in s:
    statements
    i += 1
```

可简化代码如下

```python
for i,x in enumerare(s):
    statement
```
> enumerare(s) 创建了一个迭代器
>
> 其返回值就是一个元组的序列 (0, s[0])、(1, s[1])...

循环时，同时迭代两个及其以上序列

``` python
# s、t 是两个序列
i = 0
while i <len(s) and i <len(t):
    x = s[i]
    y = t[i]
    statements
    i += 1
```

使用 zip() 简化如下

```python
for x,y in zip(s,t):
    statements
```
> zip(s,t) 将两序列组合成一个元组序列 (s[0], t[0])...
>
> s、t 不相等时，则用完长度最短的索引

语句 | 描述
---|---
pass | 不执行任何操作
break | 从循环中跳出
continue | 跳到循环的下一次迭代

* 不提供 goto 语句 *

循环结构中可以加入 else 语句
> 用途：
>
> 在代码中设置一些标志或条件; 或对这些标志或条件进行检查

循环的 else 语句在循环结束后才会执行。

如果循环体不执行，则立即执行 else 内容，否则在最后一次迭代后执行。

若使用了 break 终止了循环，则 else 不执行。

### 异常

raise 语句可以引发异常

    raise Exception([value])

try 和 except 可以捕捉异常

```python
try:
    f = open('foo')
except IOError as e:
    statements
```

出现异常时，解释器停止执行 try 语句，并寻找匹配该异常的 except 字句

pass 语句可以忽略异常

```python
try:
    do something
except IOError:
    pass
```

捕捉除与程序退出相关异常之外的所有异常

```python
try:
    do something
except Exception as e:
    error_log.write('An error occurred!\n')

except 语句不带任何异常类型，则将会捕获所有异常

try:
    do something
except:
    error_log.write('An error occurred!\n')
```

try 支持 else 语句，其紧跟在 except 语句之后
> 如果 try 中代码无错，则执行 else 语句

finally 语句为 try 代码块定义了结束操作（无论出现什么错误）

```python
f = open('foo', 'r')
try:
    do something
finally:
    # 无论前面发生什么，都会关闭文件
    f.close()
```

##### 内置异常类型

##### 定义新异常

### 上下文管理器与 with 语句

在由上下文管理器对象控制的运行时，with 语句支持上下文中执行一系列语句。

```python
with open("debug_log", "a") as f
    f.write("debuging\n")
    statements
    f.write("done\n")
```

当控制流离开 with 语句后面的代码时，with 语句将自动关闭打开的文件

### 断言与 __debug__

assert 语句可以在程序中引用调试代码
